### ISSUE TITLE
class symbols broken

### ISSUE THREAD

**Issue by thegamerx1** [helsmy/vscode-autohotkey#11]
with the latest version they dont appear
![image](https://user-images.githubusercontent.com/34986564/110489218-81e8f880-80ef-11eb-9f07-d49a8d71d379.png)

but with an old verison 0.1.2 i got from the releases page it works
![image](https://user-images.githubusercontent.com/34986564/110489316-94fbc880-80ef-11eb-833f-a3484acd46dc.png)

**Comment by helsmy** [comment]
Could you post the ahk file here? If not, I can not find out what's wrong in parser.

**Comment by thegamerx1** [comment]
The file I'm having problems with is at https://github.com/thegamerx1/ahk-libs/blob/master/Discord.ahk but it should happen with other scripts too. Can't retest it now.

**Comment by helsmy** [comment]
It is caused by {} on parameter. I add an additional check for it. It can‘t be prevented，since a regular experssion just can't perfect parse it. Try to avoid '{' and '}' if you can.
