### ISSUE TITLE
VIM Integration

### ISSUE THREAD

**Issue by pidgeon777** [helsmy/vscode-autohotkey#12]
Hello, congratulations on this project.

I would like to ask if it would be possible to integrate this AutoHotkey LSP into VIM. How could this be accomplished?

Best regards

**Comment by helsmy** [comment]
I am not familiar with vim. I only use it as a simple editor with highlight. After search on web, this is only I konw:
1. It seems that coc.nvim is the most popular language server client. So, I assume you use it.
2. Go to [vscode markertplace](https://marketplace.visualstudio.com/items?itemName=helsmy.ahk-simple-ls) to download the visx of this extension.
3. Use 7-zip or other unzip software to unzip vsix.
4. Add this configuration to your coc configuration file:
```json
"languageserver": {
  "Autohotkey": {
    "module": "your-unzip-dir/extension/server/out/server.js",
    "args": ["--node-ipc"],
    "filetypes": ["ahk"],
    "trace.server": "off",
    "documentLanguage": "no"
  }
}
```
5. restart vim, and open an ahk file  
Those may be work. I am not using vim. Those are not tested. I recommend to read doc of coc to find out how lsp works on vim.

**Comment by pidgeon777** [comment]
This is a great suggestion. I'm more than sure that it will help many other VIM users around here.

I'm testing it right now, but I'm encountering some issues. I asked here:

https://github.com/neoclide/coc.nvim/issues/3023

**Comment by pidgeon777** [comment]
I've a question, is your extension fully compliant with the Microsoft LSP Server? I mean, does your server act as a real LSP?

This means that it should support some standard LSP client commands, such as:

- Hover
- Go to definition
- Go to references
- ...

**Comment by helsmy** [comment]
All provided features is listed in readme-features. Now, only `Code Completion`, `Document symbol`,`Goto Definition`,`Signature Helper` is available. This extension is based on regular expression instead of syntax analyzing, so not all LSP features are usable.

**Comment by helsmy** [comment]
All provided features is listed in readme-features. Now, only `Code Completion`, `Document symbol`,`Goto Definition`,`Signature Helper` is available. This extension is based on regular expression instead of syntax analyzing, so not all LSP features are usable.

**Comment by pidgeon777** [comment]
Yes it is the correct one.

Anyway, I added some info which you may find interesting:

https://github.com/neoclide/coc.nvim/issues/3023
