### ISSUE TITLE
Request textDocument/signatureHelp failed

### ISSUE THREAD

**Issue by ferdinym** [helsmy/vscode-autohotkey#13]
In VS Code with helsmy.ahk-simple-ls version 0.5.5 enabled, typing `a new (` into a new line of a saved *.ahk file triggers the following error:

1. An info popup appears with "A request has failed. See the output for more information."
2. The following error is reported to the output terminal:
   ```
   [Error - 12:34:56] Request textDocument/signatureHelp failed.
   Message: Request textDocument/signatureHelp failed with message: Cannot read property 'errors' of undefined
   Code: -32603 
   ```

This can be reproduced by typing ` new`, followed by any amount of whitespace and an opening parenthesis `(`, in almost any context, but it must be preceeded by either an even or odd number of words. A few examples:
* in a new line: type `one new (` but not `one two new (`
* in comments: type `; here is something new (` but not `; this is new (`
* in assignments: type `x := new (` but not `x, y := new (`

Hope this was useful. Thanks for the work and kind regards, F

**Comment by helsmy** [comment]
thanks for you detail feedback. `new ()` is undoubtable wrong statement. So, it may cause some strange bugs on the simple parser for signture help. I will try to fix it. But, I thought it is a bit just annoying. before it is fixed, it is ok to just ignore it.
