### ISSUE TITLE
Any register for functions

### ISSUE THREAD

**Issue by Oliver-Patterson** [helsmy/vscode-autohotkey#15]
Is it possible for auto-completions and hints to be case-insensitive?

**Comment by helsmy** [comment]
It is, of course, possible. Since autohotkey is case-insensitive, it should be. But as my personal view, writing code by the completion, this doesn't effect that much. Anyway, if this is a question that make your coding not that smooth, I will add this feature.

**Comment by Oliver-Patterson** [comment]
It would be nice, thanks. Sometimes you just don’t remember which register the function is in and because of this, either the autocomplete or the hint doesn’t work.

**Comment by Oliver-Patterson** [comment]
Doesn't work with functions like this:
![image](https://user-images.githubusercontent.com/78804737/121308949-4afeca80-c90a-11eb-932a-fd55daffb121.png)

In the "correct" case:
![image](https://user-images.githubusercontent.com/78804737/121309025-5c47d700-c90a-11eb-8083-90757746b2b3.png)
