### ISSUE TITLE
Can i copy your tmLanguage.json code?

### ISSUE THREAD

**Issue by CoffeeChaton** [helsmy/vscode-autohotkey#17]
https://github.com/helsmy/vscode-autohotkey/blob/2315db78904ab325f47bcdeaa897600680c8fb5d/syntaxes/ahk.tmLanguage.json#L271-L308

I am tired of rewriting a complicated regexp, but your code repository is licensed under GPL-V3, and my embedded documentation (used for hover/completion) has copied a significant amount of examples from ahk-v1-doc, so I have chosen GPL-V2. Additionally, I am using JSON, and I cannot add comments to the beginning of the file. 

Should I update my license to V3 ?
or add something at my README.md? 
to comply with GPL requirements?

![code](https://user-images.githubusercontent.com/63182963/230781004-99c2b289-d1e8-42de-b894-a472f5986a31.png)
> reference <https://www.autohotkey.com/docs/v1/misc/CLSID-List.htm>

i am tired to write tmLanguage of [Hotkeys]<https://www.autohotkey.com/docs/v1/Hotkeys.htm#Symbols>.

**Comment by helsmy** [comment]
GPLv3 is not compatible with v2, but most of v2 project is allowed to be upgrade to v3. You can update to GPLv3. Anyway, I just pick LGPLv3 in the recommandation of [gnu.org](https://www.gnu.org/licenses/license-list.html). So, feel free to use it as long as you mark the source of the code. last, happy coding.

**Comment by CoffeeChaton** [comment]
Thank you! I will upgrade to LGPLv3.

I will write the source of the code at Readme.md .
