### ISSUE TITLE
Add lib autocompletion

### ISSUE THREAD

**Issue by thegamerx1** [helsmy/vscode-autohotkey#5]
autocomplete libs in `Documents\Autohotkey\Lib`
```autoit
#include <lib>
```

**Comment by helsmy** [comment]
On my list. May be available soon.
![图片](https://user-images.githubusercontent.com/47475699/101890535-caba0f80-3bdb-11eb-86ba-8493b905250b.png)

**Comment by helsmy** [comment]
Finished. :smile:
