### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by krasnovpro** [helsmy/vscode-autohotkey#8]
![image](https://user-images.githubusercontent.com/886676/151167650-564b96a0-d822-4f15-9684-88daba818770.png)
How to unbold the hotkeys? It looks very ugly.

**Comment by krasnovpro** [comment]
![image](https://user-images.githubusercontent.com/886676/151173225-8d331bcb-b248-4b79-bf64-249d35240e09.png)
the comment didn't become gray

**Comment by krasnovpro** [comment]
![image](https://user-images.githubusercontent.com/886676/151174328-d3b8dd76-5e2b-44c5-b2c3-7131ca60df9b.png)
why 'if' is blue, 'else', 'mousePos' and 'return' are grey?

**Comment by helsmy** [comment]
I'll try to fix this
> ![image](https://user-images.githubusercontent.com/886676/151174328-d3b8dd76-5e2b-44c5-b2c3-7131ca60df9b.png) why 'if' is blue, 'else', 'mousePos' and 'return' are grey?

And this

> ![image](https://user-images.githubusercontent.com/886676/151173225-8d331bcb-b248-4b79-bf64-249d35240e09.png) the comment didn't become gray

- And any suggestion for hotkey highlight?

**Comment by CzarOfScripts** [comment]
@helsmy 
![image](https://user-images.githubusercontent.com/78804737/151640146-0f410036-4293-4a1f-82ca-476e3d4c4aa1.png)

**Comment by CzarOfScripts** [comment]
Incorrect backlighting
![image](https://user-images.githubusercontent.com/78804737/155046286-dc2218c4-6100-433d-86ce-7db5385c6722.png)

**Comment by helsmy** [comment]
> Incorrect backlighting ![image](https://user-images.githubusercontent.com/78804737/155046286-dc2218c4-6100-433d-86ce-7db5385c6722.png)

Highlighting of continuous section is conflicted with parentheses expression. It is hard to fix this issue. There may be no perfect solution when we are using tmlanguage highligting. Highlighting based on syntax will be best solution and future plan.
