### ISSUE TITLE
inlay hints

### ISSUE THREAD

**Issue by Oliver-Patterson** [helsmy/vscode-autohotkey#9]
As I understand this is done for each language separately, can you implement it?

**Comment by helsmy** [comment]
what did you mean a inlay hints? Any picture for this?

**Comment by Oliver-Patterson** [comment]
![image](https://user-images.githubusercontent.com/78804737/107842814-b0b0cf00-6dce-11eb-8c31-3f40b71c8771.png)

**Comment by helsmy** [comment]
My answer is unfortunately no I can not for now.
As in Notice-1, this extension is mainly based on a regular expression parser. So, this extesion does not have the ability to extract all informantion of an autohotkey file. There is a syntax parser in the extension, which should have the ability to do this. But, that parser is only built for getting enough information to do correct signature help. So, that parser is not that powerful to do full parsing for the file. 
In a word, a powerful parser based on syntax analyze is needed for this high level function. I’m not so professional about it. And I don’t have so much time to do it.

**Comment by Oliver-Patterson** [comment]
I got it, thanks for the answer. I've only seen this in rust (sort of), so I didn't really hope for success, but it would be great. Thanks again. Success!)
